currentLocalization = GetLocale();
if currentLocalization == 'enUS' or currentLocalization == 'esES' or currentLocalization == 'esMX' then
	BINDING_NAME_URBANACHIEVER_TOGGLE = "Toggle Achievement Frame";
	UAComparing = "Comparing";
	UACompleted = "Completed";
	UARecentAchiev = "Recent Achievements";
	UARecentStat = "Recent Statistics";
	UAAchievEarned = "Achievements Earned";
	UASummary = "Summary";
	UAAchievement = "Achievements";
	UAStatistic = "Statistics";
	UASORT_Name = "Name";
	UASORT_Points = "Points";
	UASORT_Date = "Date";
	UASORT_Compare = "Compare";
	UATotal = "Total";
	UADisplayStatiCriter = "Display Statistic Criteria";
	UADSCTooltipStr1 = "It's ultimately useless, but can sometimes show you what you've used from a list.";
	UAColorMoney = "Color Money";
	UAShowMoneyStr1 = "Show money as";
	UAShowMoneyStr2 = "instead of";
	UADisplaySummaryCriter = "Detailed Criteria";
	UADSCTooltipStr2 = "Show the progress of individual criteria."
	UAAutoTrackA = "Auto-track timed Achievements";
	UAAutoTrackATootltip = "Will begin tracking achievements when a timer is started for one.";
	UAHelp = "Help";
	UAOMG = "OMG I'm so confused!";
	UARewardStr = "- There's a reward for completing this achievement.\n";
	UATrackedStr = "- This achievement is currently being tracked.\n";
	UAMoreStr = "- There are more achievements associated with this one. click to show/hide them.";
	UABindTrackedStr = "Shift-Click|r an achievement to add/remove it from the tracker.\n";
	UABindShowStr = "LeftClick|r an achievement title in the tracker to open it in the achievement frame.\n";
	UABindRemoveTrackedStr = "Alt-Click|r an achievement in the tracker to remove it.\n";
	UAIcon = "Icons";
	UATracker = "Tracker";
	UAReplacementFrame = "Replacement Achievement Frame";
	UAOptions = "Options";
	UAAchievementDone = "You already earned this achievement, you can't track it anymore";
	UAGuild = "Guild"
	UARecentGuildAchiev = "Recent Guild Achievements"
end