if GetLocale() == 'ruRU' then
	BINDING_NAME_URBANACHIEVER_TOGGLE = "Вкл/Выкл окно достижений";
	UAComparing = "Сравнение";
	UACompleted = "Завершено";
	UARecentAchiev = "Последние достижения";
	UARecentStat = "Последняя статистика";
	UAAchievEarned = " - получено достижений";
	UASummary = "Сводка";
	UAAchievement = "Достижения";
	UAStatistic = "Статистика";
	UASORT_Name = "Название";
	UASORT_Points = "Очки";
	UASORT_Date = "Дата";
	UASORT_Compare = "Сравнение";
	UATotal = "Всего";
	UADisplayStatiCriter = "Показывать детали статистики";
	UADSCTooltipStr1 = "Функция бесполезна, но иногда помогает удовлетворить любопытство.";
	UAColorMoney = "Окрасить индикатор денег";
	UAShowMoneyStr1 = "Показывать деньги как";
	UAShowMoneyStr2 = "вместо";
	UADisplaySummaryCriter = "Детализировать достижения";
	UADSCTooltipStr2 = "Показывает детали в целях достижения (например, количество репутации, а не просто требующуюся)."
	UAAutoTrackA = "Автоматически отслеживать достижения с таймером.";
	UAAutoTrackATootltip = "Автоматически начнет отслеживать достижение, как только будет запущен его таймер.";
	UAHelp = "Помощь";
	UAOMG = "О боже, я не знаю, что делать!";
	UARewardStr = "- За это достижение дается награда.\n";
	UATrackedStr = "- Достижение отслеживается в данный момент.\n";
	UAMoreStr = "- С этим достижением связаны еще несколько. Нажмите, чтобы показать/скрыть их.";
	UABindTrackedStr = "Shift-Click|r переключает отслеживание достижения.\n";
	UABindShowStr = "LeftClick|r по названию в трекере откроет детали достижения.\n";
	UABindRemoveTrackedStr = "Alt-Click|r по названию в трекере отменит отслеживание.\n";
	UAIcon = "Иконки";
	UATracker = "Трекер";
	UAReplacementFrame = "Улучшенное окно достижений";
	UAOptions = "Настройки";
	UAAchievementDone = "Вы уже получили это достижение, отслеживание невозможно.";
	UAGuild = "Guild"
	UARecentGuildAchiev = "Recent Guild Achievements"
end