if GetLocale() == 'zhCN' then
	BINDING_NAME_URBANACHIEVER_TOGGLE = "切换成就面板";
	UAComparing = "比较";
	UACompleted = "已完成";
	UARecentAchiev = "最近取得的成就";
	UARecentStat = "最近的统计";
	UAAchievEarned = "已完成的成就进度";
	UASummary = "总结";
	UAAchievement = "成就";
	UAStatistic = "统计";
	UASORT_Name = "名称";
	UASORT_Points = "点数";
	UASORT_Date = "日期";
	UASORT_Compare = "比较";
	UATotal = "总计";
	UADisplayStatiCriter = "显示统计条件";
	UADSCTooltipStr1 = "事实上没必要，但有时可以告诉你已经完成这项成就的哪些部分。";
	UAColorMoney = "更改金币显示方式";
	UAShowMoneyStr1 = "显示";
	UAShowMoneyStr2 = "而不是";
	UADisplaySummaryCriter = "具体条件";
	UADSCTooltipStr2 = "显示达成成就的具体条件.";
	UAAutoTrackA = "自动追踪限时成就";
	UAAutoTrackATootltip = "限时成就开始将自动计时。";
	UAHelp = "帮助";
	UAOMG = "天啊，我很迷茫！";
	UARewardStr = "- 完成这个成就有一个奖励。\n";
	UATrackedStr = "- 这是目前正在跟踪的成就。\n";
	UAMoreStr = "- 还有更多成就与这项成就相关，点击显示/隐藏它们。";
	UABindTrackedStr = "按住Shift点击|r 添加/移除对一项成就的追踪。\n"; 
	UABindShowStr = "左键单击|r 打开查看该成就。\n";
	UABindRemoveTrackedStr = "按住Alt键|r 在追踪框架中移除这一成就。\n";
	UAIcon = "图标";
	UATracker = "追踪";
	UAReplacementFrame = "更换成就框架";
	UAOptions = "选项";
	UAAchievementDone = "你已取得这项成就，无法继续追踪。";
	UAGuild = "公会"
	UARecentGuildAchiev = "Recent Guild Achievements"
end