if GetLocale() == 'zhTW' then
	BINDING_NAME_URBANACHIEVER_TOGGLE = "切換成就面板";
	UAComparing = "比較";
	UACompleted = "已完成";
	UARecentAchiev = "最近取得的成就";
	UARecentStat = "最近的統計";
	UAAchievEarned = "已完成的成就進度";
	UASummary = "總結";
	UAAchievement = "成就";
	UAStatistic = "統計";
	UASORT_Name = "名稱";
	UASORT_Points = "點數";
	UASORT_Date = "日期";
	UASORT_Compare = "比較";
	UATotal = "總計";
	UADisplayStatiCriter = "顯示統計條件";
	UADSCTooltipStr1 = "事实上没必要，但有时可以告诉你已经完成這項成就的哪些部分。";
	UAColorMoney = "更改金幣顯示方式";
	UAShowMoneyStr1 = "顯示";
	UAShowMoneyStr2 = "而不是";
	UADisplaySummaryCriter = "具體條件";
	UADSCTooltipStr2 = "顯示達成成就的具體條件.";
	UAAutoTrackA = "自動追蹤限時成就";
	UAAutoTrackATootltip = "限時成就開始將自動計時。";
	UAHelp = "幫助";
	UAOMG = "天啊，我很迷茫！";
	UARewardStr = "- 完成這個成就有一個獎勵。\n";
	UATrackedStr = "- 這是目前正在跟踪的成就。\n";
	UAMoreStr = "- 還有更多成就與這項成就相關，點擊顯示/隱藏它們。";
	UABindTrackedStr = "按住Shift點擊|r 添加/移除對一項成就的追蹤。\n";
	UABindShowStr = "左鍵單擊|r 打開查看該成就。\n";
	UABindRemoveTrackedStr = "按住Alt鍵|r 在追蹤框架中移除這一成就。\n";
	UAIcon = "圖標";
	UATracker = "追蹤";
	UAReplacementFrame = "更換成就框架";
	UAOptions = "選項";
	UAAchievementDone = "你已取得這項成就，無法繼續追蹤。";
	UAGuild = "公會"
	UARecentGuildAchiev = "Recent Guild Achievements"
end