if GetLocale() == 'deDE' then
	BINDING_NAME_URBANACHIEVER_TOGGLE = "Erfolge-Fenster ein/ausblenden";
	UAComparing = "Vergleich mit";
	UACompleted = "Errungen";
	UARecentAchiev = "Neueste Erfolge";
	UARecentStat = "Neueste Statistiken";
	UAAchievEarned = "Errungene Erfolge -";
	UASummary = "\195\156bersicht";
	UAAchievement = "Erfolge";
	UAStatistic = "Statistiken";
	UASORT_Name = "Name";
	UASORT_Points = "Punkte";
	UASORT_Date = "Datum";
	UASORT_Compare = "Vergleich";
	UATotal = "Insgesamt";
	UADisplayStatiCriter = "Statistikkriterien anzeigen";
	UADSCTooltipStr1 = "Eigentlich ist es nutzlos, aber es kann dir manchmal anzeigen, welche Dinge aus einer Liste du schon benutzt hast.";
	UAColorMoney = "Geld in Farbe anzeigen";
	UAShowMoneyStr1 = "Geldbetr\195\164ge anzeigen als";
	UAShowMoneyStr2 = "anstatt";
	UADisplaySummaryCriter = "Detaillierte Kriterien";
	UADSCTooltipStr2 = "Fortschritt einzelner Kriterien anzeigen.";
	UAAutoTrackA = "Zeitlich bemessene Erfolge automatisch verfolgen";
	UAAutoTrackATootltip = "Ein Erfolg mit Zeitvorgaben wird im Ziel-Fenster verfolgt, sobald ein Timer daf\195\188r gestartet wird.";
	UAHelp = "Hilfe";
	UAOMG = "Kehr, ich bin so verwirrt!";
	UARewardStr = "- F\195\188r diesen Erfolg gibt es eine Belohnung.\n";
	UATrackedStr = "- Dieser Erfolg wird derzeit im Ziel-Fenster verfolgt.\n";
	UAMoreStr = "- Mit diesem Erfolg sind weitere verbunden. Linksklick, um sie ein/auszublenden.";
	UABindTrackedStr = "Umschalt-Linksklick|r auf einen Erfolg, um ihn im Ziel-Fenster zu verfolgen.\n";
	UABindShowStr = "Linksklick|r auf einen Erfolgsnamen im Ziel-Fenster, um ihn im Erfolge-Fenster anzuzeigen.\n";
	UABindRemoveTrackedStr = "Alt-Linksklick|r auf einen Erfolg im Ziel-Fenster, um ihn daraus zu entfernen.\n";
	UAIcon = "Icons";
	UATracker = "Ziel-Fenster";
	UAReplacementFrame = "Ersetzt das Erfolge-Fenster";
	UAOptions = "Einstellungen";
	UAAchievementDone = "Du hast diesen Erfolg schon errungen; er kann nicht mehr verfolgt werden.";
	UAGuild = "Gilde"
	UARecentGuildAchiev = "Neueste Gildenerfolge"
end