if GetLocale() == 'koKR' then
	BINDING_NAME_URBANACHIEVER_TOGGLE = "Toggle Achievement Frame";
	UAComparing = "비교";
	UACompleted = "업적 획득";
	UARecentAchiev = "최근 업적";
	UARecentStat = "최근 갱신된 통계";
	UAAchievEarned = "획득한 업적";
	UASummary = "개요";
	UAAchievement = "업적";
	UAStatistic = "통계";
	UASORT_Name = "이름";
	UASORT_Points = "점수";
	UASORT_Date = "날짜";
	UASORT_Compare = "비교";
	UATotal = "총";
	UADisplayStatiCriter = "통계 기준 표시";
	UADSCTooltipStr1 = "불필요하긴 하지만, 가끔 목록에서 필요한 것들을 얻을수 있습니다.";
	UAColorMoney = "색깔로 금전표시";
	UAShowMoneyStr1 = "체크 후 :";
	UAShowMoneyStr2 = "체크 전 :";
	UADisplaySummaryCriter = "세부 목표";
	UADSCTooltipStr2 = "개별적인 목표의 진행 상태를 보여줍니다.";
	UAAutoTrackA = "시간 제한 업적 자동 추적";
	UAAutoTrackATootltip = "업적 타이머가 시작되면 자동으로 업적 추적을 시작합니다.";
	UAHelp = "도움말";
	UAOMG = "후~ 헷갈리네요!";
	UARewardStr = "- 이 업적을 완료하면 보상이 주어집니다..\n";
	UATrackedStr = "- 이 업적은 현재 추적중입니다.\n";
	UAMoreStr = "- 이것과 관련된 업적들이 더 있습니다. 클릭으로 보이기/숨기기";
	UABindTrackedStr = "업적을 쉬프트+클릭하여 추적창에 더하거나 뺄수 있습니다.\n";
	UABindShowStr = "추적창의 업적 제목을 좌클릭하여 업적창의 업적을 열수 있습니다.\n";
	UABindRemoveTrackedStr = "추적창의 업적을 알트+클릭하여 삭제할수 있습니다.\n";
	UAIcon = "아이콘";
	UATracker = "추적창";
	UAReplacementFrame = "추적창 초기화";
	UAOptions = "설정";
	UAAchievementDone = "이 업적을 이미 달성했으므로 더이상 추적할 수 없습니다.";
	UAGuild = "길드"
	UARecentGuildAchiev = "최근 길드 업적"
end