if GetLocale() == 'frFR' then
	BINDING_NAME_URBANACHIEVER_TOGGLE = "Afficher la fen\195\170tre de Hauts Faits";
	UAComparing = "Comparer \195\160";
	UACompleted = "Accompli";
	UARecentAchiev = "Hauts Faits r\195\169cents";
	UARecentStat = "Statistiques r\195\169centes";
	UAAchievEarned = "Hauts Faits accomplis";
	UASummary = "R\195\169sum\195\169";
	UAAchievement = "Hauts Faits";
	UAStatistic = "Statistics";
	UASORT_Name = "Nom";
	UASORT_Points = "Points";
	UASORT_Date = "Date";
	UASORT_Compare = "Compar\195\169";
	UATotal = "Total";
	UADisplayStatiCriter = "Afficher les crit\195\168res des Statistiques";
	UADSCTooltipStr1 = "C'est normalement inutile, sauf dans certains cas o\195\185 cela vous montre ce que vous pouvez utiliser dans une liste";
	UAColorMoney = "Couleur de l'argent";
	UAShowMoneyStr1 = "Montrer l'argent au format";
	UAShowMoneyStr2 = "au lieu de";
	UADisplaySummaryCriter = "Crit\195\168res d\195\169taill\195\169s";
	UADSCTooltipStr2 = "Montrer la progression de chaque crit\195\168re.";
	UAAutoTrackA = "Auto-Suivi des Hauts Faits tim\195\169s";
	UAAutoTrackATootltip = "Suivera automatiquement un Haut Fait quand son timer d\195\169marrera.";
	UAHelp = "Aide";
	UAOMG = "Mon dieu, je suis tellement d\195\169sol\195\169!";
	UARewardStr = "- Il y a une r\195\169compense pour l'accomplissement ce Haut Fait.\n";
	UATrackedStr = "- Ce Haut Fait est en cours de suivi.\n";
	UAMoreStr = "- Il y a des Hauts Faits associ\195\169s \195\160 celui-l\195\160. Cliquer pour les montrer ou les cacher.";
	UABindTrackedStr = "Maj-clic|r sur un Haut Fait pour l'ajouter ou le retirer des Hauts Faits suivis.\n";
	UABindShowStr = "Clic-gauche|r sur le titre d'un Haut Fait suivi pour l'ouvrir dans la fen\195\170tre de Hauts Faits.\n";
	UABindRemoveTrackedStr = "Alt-Clic|r sur un Haut Fait suivi pour d\195\169sactiver son suivi.\n";
	UAIcon = "Ic\195\180nes";
	UATracker = "Suivi"
	UAReplacementFrame = "Fen\195\170tre de Hauts Faits am\195\169lior\195\169e";
	UAOptions = "Options";
	UAAchievementDone = "Vous avez d\195\169j\195\160 accomplis ce Haut-Fait, vous ne pouvez donc plus le suivre.";
	UAGuild = "Guilde"
	UARecentGuildAchiev = "Hauts Faits de guilde r\195\169cents"
end