-- Author      : Administrator
-- Create Date : 9/13/2008 10:16:36 AM
SliceCmdr_BarTextures = {
	['Aluminum'] = 'Interface\\AddOns\\SliceCommander\\Images\\Aluminium.tga',
	['BantoBar'] = 'Interface\\AddOns\\SliceCommander\\Images\\BantoBar.tga',
	['Blizzard'] = 'Interface\\TARGETINGFRAME\\UI-TargetingFrame-BarFill.blp',
	['Flat'] = 'Interface\\AddOns\\SliceCommander\\Images\\Flat.tga',
    ['Gloss'] = 'Interface\\AddOns\\SliceCommander\\Images\\Gloss.tga',
    ['HealBot'] = 'Interface\\AddOns\\SliceCommander\\Images\\HealBot.tga',
    ['LiteStep'] = 'Interface\\AddOns\\SliceCommander\\Images\\LiteStep.tga',
    ['Runes'] = 'Interface\\AddOns\\SliceCommander\\Images\\Runes.tga',
	['Smooth'] = 'Interface\\AddOns\\SliceCommander\\Images\\Smooth.tga',
};

SliceCmdr_Sounds = {
	["Price is WRONG"] = "Interface\\AddOns\\SliceCommander\\Audio\\PriceIsWrong.mp3",
	["Waaaah"] = "Interface\\AddOns\\SliceCommander\\Audio\\Old Trumpet A 01.mp3",
	['BassDrum'] = 'Interface\\AddOns\\SliceCommander\\Audio\\6OP00084.mp3',
	['Tambourine'] = 'Interface\\AddOns\\SliceCommander\\Audio\\tambourine.mp3',
	['Cowbell'] = 'Interface\\AddOns\\SliceCommander\\Audio\\cowtown.mp3',
	['SliceClick'] = 'Interface\\AddOns\\SliceCommander\\Audio\\FXHit15.mp3',
	['BoomBoomClap'] = 'Interface\\AddOns\\SliceCommander\\Audio\\HoleA.mp3',
	['Marching Band'] = 'Interface\\AddOns\\SliceCommander\\Audio\\OldDrums2.mp3',
	['High Hat 4'] = 'Interface\\AddOns\\SliceCommander\\Audio\\perc09_HH.mp3',
	['BoomBoomThak'] = 'Interface\\AddOns\\SliceCommander\\Audio\\RawB.mp3',
	['Arpeggiator C2'] = 'Interface\\AddOns\\SliceCommander\\Audio\\Arp31-C2.mp3',
	['Arpeggiator C3'] = 'Interface\\AddOns\\SliceCommander\\Audio\\Arp31-C3.mp3',
	['Arpeggiator C4'] = 'Interface\\AddOns\\SliceCommander\\Audio\\Arp31-C4.mp3', 
	['ScratchShot'] = 'Interface\\AddOns\\SliceCommander\\Audio\\ScratchShot.mp3', 
	['StunningHit'] = 'Interface\\AddOns\\SliceCommander\\Audio\\StunningHit.mp3', 
	['DNBLoop4'] = 'Interface\\AddOns\\SliceCommander\\Audio\\DNBLoop4.mp3',
	['DNBLoop2'] = 'Interface\\AddOns\\SliceCommander\\Audio\\DNBLoop2.mp3',
	['Scratch4'] = 'Interface\\AddOns\\SliceCommander\\Audio\\Scratch4.mp3',
	['You Spin Me'] = 'Interface\\AddOns\\SliceCommander\\Audio\\youspin.mp3',
	["What's the Deal?"] = 'Interface\\AddOns\\SliceCommander\\Audio\\whats-the-deal.mp3',
	['ClubBeatJ'] = 'Interface\\AddOns\\SliceCommander\\Audio\\ClubBeatJ.mp3',
	['Growl'] = 'Interface\\AddOns\\SliceCommander\\Audio\\growl.mp3',
	['OH YEAH'] = 'Interface\\AddOns\\SliceCommander\\Audio\\OH-YEAH.mp3',
	['Shaker'] = 'Interface\\AddOns\\SliceCommander\\Audio\\shaker.mp3',
	['Pop'] = 'Interface\\AddOns\\SliceCommander\\Audio\\pop.mp3',
	['Drum Rattle'] = 'Interface\\AddOns\\SliceCommander\\Audio\\drumrattle.mp3',
	['Ping'] = 'Interface\\AddOns\\SliceCommander\\Audio\\pingit.mp3',
	['Switch On/Off'] = 'Interface\\AddOns\\SliceCommander\\Audio\\switch-on-off.mp3',
	['Eth Perc Short'] = 'Interface\\AddOns\\SliceCommander\\Audio\\perc-short.mp3',
	['Eth Perc Long'] = 'Interface\\AddOns\\SliceCommander\\Audio\\perc-long.mp3',
	["None"] = "",
};

SliceCmdr_Timer = {
	["Price is WRONG"] = 4.57,
	["Waaaah"] = 3.891,
	['BassDrum'] = 1.515,
	['Tambourine'] = 0.365,
	['Cowbell'] = 0.783,
	['SliceClick'] = 2.37,
	['BoomBoomClap'] = 4.48,
	['Marching Band'] = 4.832,
	['High Hat 4'] = 1.645,
	['BoomBoomThak'] = 2.429,
	['Arpeggiator C2'] = 0.25,
	['Arpeggiator C3'] = 0.548,
	['Arpeggiator C4'] = 0.548, 
	['ScratchShot'] = 1.358, 
	['StunningHit'] = 2.69, 
	['DNBLoop4'] = 1.54,
	['DNBLoop2'] = 0.25,
	['Scratch4'] = 2.69,
	['You Spin Me'] = 7.522,
	["What's the Deal?"] = 1.383,
	['ClubBeatJ'] = 1.75,
	['Growl'] = 1.97,
	['OH YEAH'] = 2.847,
	['Shaker'] = 1.43,
	['Pop'] = 0.208,
	['Drum Rattle'] = 1.122,
	['Ping'] = 0.365,
	['Switch On/Off'] = 390,
	['Eth Perc Short'] = 1.41,
	['Eth Perc Long'] = 2.89,
	["None"] = 0,
};

SliceCmdr_SoundMenu = {
	['Fail'] = { 'None', 'Waaaah', 'BassDrum', 'Price is WRONG', 'ScratchShot', 'StunningHit', "What's the Deal?", 'Growl', 'Switch On/Off', 'Eth Perc Short', 'Eth Perc Long', 'Ping', 'Drum Rattle', 'Pop', 'Shaker' },
	['Tick'] = { 'None', 'Switch On/Off', 'Eth Perc Short', 'Eth Perc Long', 'Ping', 'Drum Rattle', 'Pop', 'Shaker', 'Tambourine', 'Cowbell', 'Arpeggiator C2', 'Arpeggiator C3', 'Arpeggiator C4', 'DNBLoop2','ClubBeatJ','Growl' },
	['Apply'] = { 'None', 'Switch On/Off', 'Eth Perc Short', 'Eth Perc Long', 'Ping', 'Drum Rattle', 'Pop', 'Shaker', 'SliceClick', 'BoomBoomClap', 'Marching Band', 'High Hat 4', 'BoomBoomThak', 'StunningHit', 'DNBLoop4', 'You Spin Me', 'OH YEAH'},
	['Energy'] = { 'None','Switch On/Off', 'Eth Perc Short', 'Eth Perc Long', 'Ping', 'Drum Rattle', 'Pop', 'Shaker', 'Arpeggiator C2', 'Arpeggiator C3', 'Arpeggiator C4', 'ScratchShot', 'DNBLoop2', 'Scratch4', 'StunningHit', 'ClubBeatJ' },
	['All'] = { 'None', 'Price is WRONG', 'Waaaah', 'BassDrum', 'Tambourine', 'Cowbell', 'SliceClick', 'BoomBoomClap', 'Marching Band', 'High Hat 4', 'BoomBoomThak', 'Arpeggiator C2', 'Arpeggiator C3', 'Arpeggiator C4', 'ScratchShot', 'StunningHit', 'DNBLoop4', 'DNBLoop2', 'Scratch4', 'You Spin Me', "What's the Deal?", 'ClubBeatJ', 'Growl', 'OH YEAH', 'Shaker', 'Pop', 'Drum Rattle', 'Ping', 'Switch On/Off', 'Eth Perc Short', 'Eth Perc Long' }
}